package exceptionHandling;

public class NestedtryCatch {

	String name = "pratik";
	public static void main(String[] args) {
		// TODO Auto-generated method stub
		
		NestedtryCatch nc= new NestedtryCatch();
		
		int i = 10;
		nc = null;
		
		try {
		
			
			int p = i/0;
			System.out.println(nc.name);
			
		
		}
		
		catch(ArithmeticException e) {
			System.out.println(e.getMessage());
			
		}
		
		catch(NullPointerException e)
		{
			System.out.println(e.getMessage());
		}
	}

}
